<a href="https://colab.research.google.com/github/satishpr9/machine_learning/blob/main/pytorch_nn_module.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import torch.nn as nn

In [ ]:
class Model(nn.Module):
  def __init__(self,nums_features):
    super().__init__()
    self.linear=nn.Linear(nums_features,3)
    self.rule=nn.ReLU()
    self.linear1=nn.Linear(3,1)
    self.sigmoid=nn.Sigmoid()

   # self.network =nn.Sequential(
    #    nn.Linear(nums_features,3)
    #nn.ReLU()
    #nn.Linear(3,1)
    #nn.Sigmoid()
    #)
  def forward(self,features):
    out=self.linear(features)
    out=self.rule(out)
    out=self.linear1(out)
    out=self.sigmoid(out)
    return out

In [ ]:
#create dataset
features=torch.rand(10,6)
#create  model
model=Model(features.shape[1])
#call model for forward pass
model(features)

tensor([[0.4318],
        [0.4390],
        [0.4328],
        [0.4574],
        [0.4481],
        [0.4318],
        [0.4318],
        [0.4541],
        [0.4431],
        [0.4318]], grad_fn=<SigmoidBackward0>)

In [ ]:
model.linear.weight

Parameter containing:
tensor([[-0.0157, -0.3297, -0.1587,  0.0546,  0.0909, -0.1610],
        [-0.1627, -0.0346, -0.2760,  0.2414, -0.2728, -0.3768],
        [-0.0356, -0.1046, -0.2979, -0.3652, -0.1517,  0.1302]],
       requires_grad=True)

In [ ]:
model.linear.bias

Parameter containing:
tensor([-0.3268, -0.1681,  0.3085], requires_grad=True)

In [ ]:
from torchinfo import summary
summary(model, input_size=(10,6))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   21
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 25
Trainable params: 25
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00